- pkgs/clang/bug-14435.patch
- pkgs/gecko.nix
- release.nix
- Fix Gecko mozconfig.
- Fix clang compiler to use libc++ provided with llvm, instead of using gcc 5.3 headers.
- Add debugging tools in the nix-shell.
> Improve/Fix Gecko nix expression. (build, clang, rr & gdb)

- rust-overlay.nix
This prevents the system-wide `/bin/sh` to be used, which causes trouble
on travis-ci and the installed dash.
Fixes #23
> rust-overlay: patch SHEBANGS in install.sh

- rust-overlay.nix
Fixes #32.
I've also had to override `buildRustPackage` to pass the environment variable `CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER="gcc";`, because otherwise Cargo (?) passes `-C linker=arm-linux-gnueabihf-gcc` to rustc and building crates with native components fails. I've used another overlay to do this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/nixpkgs-mozilla/34)
> rust-overlay.nix: use armv7 triple when on armv7

- rust-overlay.nix
Allows users to avoid builtins.fetchurl when targeting a specific version of Rust.
> rust-overlay.nix: add fromManifestFile

- pkgs/firefox-nightly-bin/update.nix
Use https, with `curl` piping to `xidel` (which doesn't support https).
Ran into a problem where the tar file had the wrong sha512 over http via. curl/wget (confirmed on two machines on different networks).
> Use HTTPS to download nigthly

- firefox-overlay.nix
The `self.gnupg` derivation currently defaults to `gnupg-2.1` which does not have the `gpg2` and `gpgv2` commands. They are simply called `gpg` and `gpgv`.
This is just a fix to allow Firefox to be installed from this overlay.
> Use gpg and gpgv commands

- servo-overlay.nix
self.rustUnstable is undefined
Fixes #59
> servo: remove nil reference

- pkgs/firefox-nightly-bin/default.nix
Fixes the error mentioned in(second comment): https://github.com/mozilla/nixpkgs-mozilla/pull/60
> Fixes error with wrong import path for firefox-bin

- pkgs/firefox-nightly-bin/sources.nix
I just checked that the error was gone for: https://github.com/mozilla/nixpkgs-mozilla/pull/62
But apparently, the version does not exist anymore for downloading. Nightly is anyway version 57 currently.
> Updates pinned nightly to latest release

- README.rst
- firefox-overlay.nix
- pkgs/gecko/default.nix
Fix:
- Pin rustc version to avoid error during webrender / stylo compilations.
- bindgen arguments are now provided to the shell throught the $MOZCONFIG_TEMPLATE, this ensure that stylo compilation works.
- clang is removes from the list of dependencies in order to avoid confusing the toolchain. Instead, clang arguments for bindgen are provided in the $MOZCONFIG_TEMPLATE file.
- Add missing dependencies reported by the configure phase.
New feature:
- NIX_SHELL_HOOK environment variable can be use to avoid repeating your-self on the command line. Thus, one can define this variable with some script content, which exports a bunch of environment variables such as MOZ_LOG and others.
- Proper README.rst documentation.
Edit: remove comment about unset-ing noisy environment variables.
Edit: Add …
> Improve nix-shell environment for developing Gecko.

- rust-src-overlay.nix
I spent considerable time to use the overlay and install rust including rust-src via nix-env.
It seeems like the general problems is common, even though other user prefer a nix-shell environment: #51, #19
If you like this pull request, this should probably be added to the README.rst as an option.
> rust-src-overlay.nix: adds rust-src as an extension to all channels

- README.rst
Just an additional example for those of us who would like a specific rust nightly version.  This took a while for me to figure out!
> example of retrieving a specific nightly version

- pkgs/VidyoDesktop/default.nix
Thanks to @washort for telling me how to get it running again.
> VidyoDesktop requires libGL on unstable

- compilers-overlay.nix
- firefox-overlay.nix
- pkgs/gecko/default.nix
- release.nix
- rust-overlay.nix
* Add newer versions of gcc to the list of compilers, for bisecting compilers.
* Downgrade to python 3.5 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1465035 )
* Add missing X dependencies. ( https://bugzilla.mozilla.org/show_bug.cgi?id=1456183 )
* Fix clang compilation for SpiderMonkey (not tested on Gecko yet )
> Update gecko build environment.

- rust-overlay.nix
This helper has been requested for in `#rust-offtopic`, for using the channel generation commands easily from the command line with `nix-shell -p`.
Maybe it could even be improved by making intermediate functions derivation functors, so that arguments 2 and 3 are optional? if you think it'd be better I can try to implement it :)
> Add helper Rust builder

- rust-overlay.nix
This commit adds a new target to `rust-overlay.nix`. This target will be used to configure a Firefox for android build.
> Add android target to rust-overlay.

- firefox-overlay.nix
- pkgs/cbindgen/default.nix
- pkgs/gecko/default.nix
This pull request adds nodejs and cbindgen dependencies to gecko dev environment.
Unfortunately, nixos-18.03 does not have `nodejs-8_x` as the default, and not does include `rust-cbindgen` yet, as opposed to nixos-unstable. Therefore, this commit does a bit of work-around to work on top of nixos-18.03 by importing them from Nixpkgs, or comparing the versions to check if we have the desired version or not.
> Add nodejs and cbindgen dependency for building Firefox.

- default.nix
- overlays.nix
- package-set.nix
This extracts the overlays list, to be used by both the combined
overlay and the package set representation.
It is meant to be used with nix-community/NUR#32
> Allow usage as package set instead of overlay

- firefox-overlay.nix
This does not evaluate properly without this as I get:
```
error: attempt to call something which is not a function but a set
```
I'm no expert but it would seem there is a precedence issue in the expression as it was written.
> Fix rust-cbindgen expression.

- pkgs/cbindgen/default.nix
> Bumps cbindgen to 0.6.2

- firefox-overlay.nix
This pull request fixes the second issue reported in #112, by providing a newer `rustPlatform` based on the latest rustc provided by the rust overlay.
It also adds some logic to select `rust-cbindgen-0_6_2` only if it is newer than what is provided by Nixpkgs.
> Cbindgen 0.6.2: Fix rustPlatform and gecko input.

- pkgs/gecko/default.nix
This patch is used to expose clang and bindgen configs to be used on the command line, when building the JS Shell with its configure script.
> Add 2 environment variables for compiling the JS Shell with Cranelift.

- pkgs/gecko/default.nix
The nix-shell will inherit the default set of variable from the stdenv. Unfortunately, this set AS=as which no longer works after the resolution of https://bugzil.la/1397263 .
> Unset AS=as

- pkgs/git-cinnabar/default.nix
git-cinnabar 0.5.0 was released on August 11. https://github.com/glandium/git-cinnabar/releases/tag/0.5.0
There were some changes to the Makefile that I try to work around here:
- [Try to make sure that git-core submodule is up to date](https://github.com/glandium/git-cinnabar/commit/5cf2df3ffe4f33674719064953bd5ac568404794). Add git to the build-inputs so some of these calls succeed, but then comment out most of the actual work that would happen to do the update. We have `fetchSubmodules=true` so there's no real need for it anyhow.
- [Change the default build rule when running plain `make`](https://github.com/glandium/git-cinnabar/commit/2a327c003d6af49f62fac508cdc4781cece0bcea#diff-b67911656ef5d18c4ae36cb6741b7965). To be honest I'm not sure if I'm handling this correctly, but just …
> Update git-cinnabar to 0.5.0

- README.rst
Now that #124 and #122 have landed, add a section to the documentation to tie it all together.
> Add another section about submitting Firefox patches

- pkgs/VidyoDesktop/default.nix
> Use the CERN portal to download Vidyo 3.6.3

- rust-overlay.nix
The Rust overlay didn't work with the latest nightly Rusts, because of a faulty "component". This fixes it, at least temporarily. Incidentally, this also fixes #92, because the latest nightly Rust have apparently fixed the toolchain.
Once this gets merged, we'll be just one step away from Rust-WASM Nix expression to use instead of the current NPM-based pipeline.
> rust-overlay: fixing the latest nightly Rusts

- pkgs/VidyoDesktop/default.nix
Instead of using a 3rd party URL, we can use Vidyo's server.
> Change Vidyo URL

- firefox-overlay.nix
- pkgs/cbindgen/default.nix
This is required now since
https://bugzilla.mozilla.org/show_bug.cgi?id=1503401.
While we're here, rewrite the version-checking logic to simplify.
> Bump cbindgen to 0.6.7

- pkgs/gecko/default.nix
This was introduced in https://bugzilla.mozilla.org/show_bug.cgi?id=1501796.
> nasm is now required to build Gecko

- rust-overlay.nix
There's no point copying the src tarball to a remote build server, then copying back the entire unpacked contents after just a little twiddling.
This makes builds significantly faster for those of us with remote builders configured, since the network transfers can be much slower than the actual derivation build step.
> Don't "build" Rust packages on a remote builder

- lib/parseTOML.nix
This fix is taken from @spacefrogg solution described in https://github.com/mozilla/nixpkgs-mozilla/issues/148#issuecomment-455314172 and to which I added a way to avoid crashing if the value is ever read afterwards.
We should probably use `fromJSON` to decode the TOML list into a Nix list, if we want to use the list of profile as well to better mimic `rustup`.
> Accept TOML list in fromTOML function

- firefox-overlay.nix
Nixpkgs might not provide a version of valgrind which is new enough. Bump it locally for gecko-dev to the version 3.14.
> valgrind: -> 3.14

- firefox-overlay.nix
- pkgs/cbindgen/default.nix
Bump cbindgen version for Gecko development.
> cbindgen: 0.6.7 -> 0.6.8

- pkgs/gecko/default.nix
llvm-objdump is now required for building Gecko. It was supposed to be available already as it is packaged with llvm-config, but llvm-config was not used as it could not provide clang information.
> Gecko: Add llvm dependency for llvm-objdump.

- rust-overlay.nix
Thanks @bbigras for the report at https://github.com/rust-lang/rust/issues/57518 and @nagisa for the fix which is implemented in this patch.
> Fix #152 - Rust: Remove add-needed libstdc++ line.

- pkgs/gecko/default.nix
- release.nix
This patch ensure that the release.nix script can produce a build environment which is working well on ARM64 systems.
> Gecko dev: Make a working dev-env on ARM64.

- pkgs/VidyoDesktop/builder.sh
- pkgs/VidyoDesktop/default.nix
with latest unstable channel /opt folder (where vidyo is copied) is
ignored since there is already something there from chroot derivation.
this solution is clearly a hack and i'm open to suggestion how to fix
this properly. until then this should be good enough.
> vidyo: fix to vidyo work with current nixos unstable

- pkgs/cbindgen/default.nix
I'm not sure why the cargo hash didn't change.
This is the version currently required to build Firefox.
> Update cbindgen to 0.8.2

- pkgs/gecko/default.nix
As of 19.03, the "proto" packages (printproto, renderproto, etc.) no
longer exist. https://github.com/NixOS/nixpkgs/pull/53127 made it
unnecessary to depend on each individual fooproto derivation. Instead
it's sufficient to just depend on xorgproto.
The old names are still necessary for 18.09, so leave them for now.
> Adapt to changes in xorg protos

- rust-overlay.nix
Using nixpkgs-mozilla Rust compiler with buildRustPackage in recent
Nixpkgs versions will result in:
> error: attribute 'platforms' missing, at nixpkgs/pkgs/build-support/rust/default.nix:164:17
> (use '--show-trace' to show detailed location information)
This change fixes that error.
> rust: set meta.platforms

- rust-overlay.nix
On lorri (https://github.com/target/lorri/)
this decreases the time to instantiate the shell
from
5.03user 0.24system 0:05.59elapsed 94%CPU
to
2.67user 0.27system 0:03.25elapsed 90%CPU
cc @nbp
> rust-overlay: use builtins.fromTOML if possible.

- firefox-overlay.nix
The `name` argument has been removed from the Firefox wrapper in the master version of nixpkgs:
https://github.com/NixOS/nixpkgs/commit/d34d84a61da7cf332e470b65ab05f2d995026090
This causes the overlay to fail with the following error:
```
error: 'wrapper' at /nix/store/2h5z1dm03waymz8b383szl5bc8a21f74-nixos-20.03pre203172.0ee0489d42e/nixos/pkgs/applications/networking/browsers/firefox/wrapper.nix:21:5 called with unexpected argument 'name', at /nix/store/2h5z1dm03waymz8b383szl5bc8a21f74-nixos-20.03pre203172.0ee0489d42e/nixos/lib/customisation.nix:69:16
```
I have replaced it with `pname` in this PR.
> Update wrapFirefox call to remove name argument

- rust-overlay.nix
This reverts commit a26d388082fcd470fa05e3276c9405dc306fdf16.
Resolves #181.
> Revert "rust-overlay: fixing the latest nightly Rusts"

- README.rst
- rust-overlay.nix
This changes the parsing of a rust-toolchain file, so that specifications like `"nightly"` or `"1.34.0"` are actually accepted.
> rust-overlay: support rust-toolchain file without archive date

- pkgs/cbindgen/default.nix
Newer cbindgen is now needed to build firefox.
I pulled this from nixpkgs, but had to comment out the Darwin `Security` package as it is not yet available even on nixos-unstable. If that breaks MacOS builds, we may need to copy it over too, but I'm inclined to leave that for someone who has a Mac to test on.
> cbindgen: 0.9.1 -> 0.13.1

- rust-overlay.nix
`rustdoc` did not detect `core` for other targets as it was handled differently from `rustc`. I tested locally that this fix works. Apparently this also fixes some whitespace.
> Fix rustdoc with non-default targets

- rust-overlay.nix
Parentheses were necessary for precedence.
> rust-overlay.nix: fix example in comments

- rust-overlay.nix
Fixes: https://github.com/mozilla/nixpkgs-mozilla/issues/225
> rust-overlay: Fix missing libz.so.1

- pkgs/git-cinnabar/default.nix
- release.nix
Old patch I forgot to submit. I have not yet tried 0.5.5 which has been released since.
> git-cinnabar: 0.5.2 -> 0.5.4

- rust-overlay.nix
This extends #197 to better support cross compiling. We need both cross and native rust comperly to build properly.
/cc @nbp
> Support cross compiling rust

- firefox-overlay.nix
This is sort of an experiment for now until I get more feedback.
This is a small tweak that allows me to consume this overlay in [flake-firefox-nightly](https://github.com/colemickens/flake-firefox-nightly) and expose a `--pure-eval`-able `firefox-nightly` attribute for flakes users that want to pin everything and have a purely eval-able system.
Fundamentally this exposes functions so that an outside caller can determine latest information and checksums and then re-instantiate that exact version purely later. (See `update.sh` in **flake-firefox-nightly** for more of an idea of how it works.)
> firefox-overlay: expose more for flakes overlay/users

- firefox-overlay.nix
From `python ./mach build`:
```
0:00.57 ERROR: One of the following Python versions are required:
0:00.57 ERROR: * Python 2.7.3 or greater
0:00.57 ERROR: * Python 3.6.0 or greater
0:00.57 ERROR: You are running Python 3.5.9.
```
> Use Python 3.6 instead of Python 3.5 for firefox-overlay

- pkgs/gecko/default.nix
According to [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1234092), Firefox removed gstreamer support a few years ago.
> Remove unused gstreamer dependency

- rust-overlay.nix
gdb's auto-load mechanism resolves symlinks before checking if each file is
allowed via auto-load-safe-path. we fix this by copying over those files into the
final derivation, similar to {rustc,rustdoc}.
The issue can be easily reproduced:
```
$ rust-gdb target/debug/program
(...)
Reading symbols from target/debug/program...
warning: File "/nix/store/i4bi7d6q68m8kjqqx2j9zfry451sllbq-rust/lib/rustlib/etc/gdb_load_rust_pretty_printers.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/nix/store/vran8acwir59772hj4vscr7zribvp7l5-gcc-9.3.0-lib:/nix/store/q1vicr5q8xkaajjlxd7v4ri4axhisaan-rust-1.45.0-nightly-2020-05-31-5fd2f06e9/lib/rustlib/etc".
To enable execution of this file add
add-auto-load-safe-path …
```
> rust-overlay.nix: fix pretty-printers for rust-gdb

- rr-overlay.nix
Fixes the error:
```
error: while evaluating anonymous function at /nix/store/…/nixos/lib/customisation.nix:77:32,
called from /nix/store/…/rr-overlay.nix:5:8:
while evaluating 'makeOverridable' at /nix/store/…/nixos/lib/customisation.nix:67:24,
called from /nix/store/…/nixos/lib/customisation.nix:77:41:
anonymous function at /nix/store/…/nixos/pkgs/development/tools/analysis/rr/default.nix:1:1
called with unexpected argument 'stdenv',
at /nix/store/…/nixos/lib/customisation.nix:69:16
```
As of https://github.com/NixOS/nixpkgs/commit/b60b4023d72b468ec734fba83d902a9b9f6a3625, `rr` in nixpkgs now expects a `gcc9Stdenv` argument instead of a `stdenv` argument.
> Fix `rr-overlay.nix` for modern nixpkgs

- rust-overlay.nix
Before:
```console
$ nix-shell -p '(rustChannelOf { date = "2017-02-02"; }).rustc' --run 'rustc --version'
error: attribute 'xz_url' missing, at /home/anders/nix/nixpkgs-mozilla/rust-overlay.nix:100:31
(use '--show-trace' to show detailed location information)
```
After:
```console
$ nix-shell -p '(rustChannelOf { date = "2017-02-02"; }).rustc' --run 'rustc --version'
rustc 1.16.0-nightly (24055d0f2 2017-01-31)
```
> rust-overlay: Allow running ancient pre-xz versions

- firefox-overlay.nix
Fixes this error on current nixos-unstable:
```console
$ nix build -Lf '<nixpkgs>' latest.firefox-bin
error: 'wrapper' at /nix/store/bgamkl5agk73pncifps984yil4hfhvkk-nixos-21.11pre308541.6fc5211eddd/nixos/pkgs/applications/networking/browsers/firefox/wrapper.nix:23:5 called with unexpected argument 'browserName', at /nix/store/bgamkl5agk73pncifps984yil4hfhvkk-nixos-21.11pre308541.6fc5211eddd/nixos/lib/customisation.nix:69:16
```
See NixOS/nixpkgs@711d674e1322a8ccdbf985322468da87a141bc9c.
> firefoxVersion: Fix for upstream browserName → applicationName rename

- firefox-overlay.nix
By default the Nix expression inherit from Nixpkgs to set the list of libraries and make the binary work.
However, the Nixpkgs version does not yet depend on `libXtst` which would prevent Firefox from running if lacking.
This modification extend the `libPath` by adding the path to `libXtst`. While not overridable, this would temporarily circuvent the problem of not being able to run Firefox.
> firefox: Firefox nightly depends on libXtst.

- firefox-overlay.nix
Reverts mozilla/nixpkgs-mozilla#268
This does not seems to be necessary anymore, and this method seems to have caused issues with Nixpkgs 21.05. (#270 )
> Revert "firefox: Firefox nightly depends on libXtst."

- firefox-overlay.nix
This reverts commit 728f3df8936c74ca5417259bb602e9bac66e3e60.
Apparently `libXtst` is still mandatory and we have to find another way to extend the libPath which is compatible with Nixpkgs 21.05.
> Revert "Revert "firefox: Firefox nightly depends on libXtst.""

- README.rst
- firefox-overlay.nix
- release.nix
Gecko needs `zstandard` package, which first appears in Python-3.8.
Also follows up to #273 a bit and adds an important note to the readme.
> Require Python38 instead of Python36

- README.rst
It's no longer just a wrapper around Arcanist. It's also now officially packaged - 
https://github.com/NixOS/nixpkgs/pull/146430
> Update moz-phab description

- README.rst
- flake.nix
Resurrects #248. This PR adds flake support by exposing the available overlays as flake outputs. It deliberately does not include the packages themselves as outputs, because doing so would require pinning the flake to a certain revision of Nixpkgs via a `flake.lock` file.
> Add initial flake support

- flake.nix
The repository flake currently tries to import `rr-overlay`, without an extension, so here's a fix for that typo.
> Fix Importing `rr-overlay.nix`

- firefox-overlay.nix
Fixes window to desktop entry mapping on Plasma, and probably just about every other X11 desktop. There's some crimes to get to the actual wrapped `wrapFirefox`'s signature, but other than that it seems not terrible.
> firefox-overlay: pass wmClass to wrapFirefox if supported

- firefox-overlay.nix
- lib/parseTOML.nix
- pkgs/cbindgen/default.nix
- pkgs/gcc-4.7/default.nix
they may be removed from the language since theres a experimental feature called `no-url-literals`
> remove url literals

- rust-overlay.nix
Rust changed the way the SYSROOT is determined in: https://github.com/rust-lang/rust/pull/103660
Before this change the SYSROOT was determined based on the rustc executable. Now it is determined based on the librustc_driver-*.so file. This pr fixes the detection by copying the library to the derivation as we have done it for the rustc executable.
> Fix SYSROOT detection on latest nightly

- rust-overlay.nix
It was removed in https://github.com/NixOS/nixpkgs/pull/210993
> rust-overlay: drop `header` function

- firefox-overlay.nix
The GPG key matches the one published on
https://blog.mozilla.org/security/2023/05/11/updated-gpg-key-for-signing-firefox-releases/
> Update the GPG key which is used to sign Firefox releases.

- firefox-overlay.nix
There's some weird new behavior with keyring paths and keyboxd, so avoid the entire footgun by just explicitly telling it what key to use.
> Update gpg incantations to work with 2.4.1

- README.rst
It looks like the README is somewhat out of date - `nix flake show` gives the correct information, but it's probably best to keep this up to date - Thanks!
> doc: fix flake overlay path description

- rust-overlay.nix
When building rust-src like in
```
nix build --impure -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/tags/23.05.tar.gz --argstr PWD $PWD --expr \
'{ PWD }:(import <nixpkgs> { overlays = (builtins.getFlake PWD).overlays.rust ];}).latest.rustChannels.stable.rust-src' \
-L --out-link rust-src-stable
```
the build failed since commit https://github.com/mozilla/nixpkgs-mozilla/commit/f6fe8508b0910b84b74c0e0bfa0ff8593e77d470 with an error like
```
chmod: cannot access '/nix/store/rawpkwl6b5h2qqv41w8yqgpayp89q9xa-rust-src-1.71.0-2023-07-12-8ede3aae2/bin/rustc': No such file or directory
```
because, indeed this file is not present in rust-src build output.
This commit moves the failing commands inside the conditional block so that they are only executed when the file is present.
\
\ …
> Fix #304 build rust-src from overlay

- firefox-overlay.nix
These are included in every supported version of nixpkgs, so we no longer need them here.
> firefox-nightly-bin: remove old workarounds

- firefox-overlay.nix
- pkgs/firefox-nightly-bin/update.nix
Bug [1710599](https://bugzilla.mozilla.org/show_bug.cgi?id=1710599) has changed linux builds from bz2 to xz. 
The change will ride the train and will eventually hit beta and release, at which point all the file references should also point to .xz (left a comment to reflect this).
Closes #334
> Update extension of nightly builds to xz

- rust-overlay.nix
When using `nixpkgs-unstable` or NixOS 24.11 (not released as of writing), using the rust overlay leads to the following deprecation warning:
```
evaluation warning: `rust.toRustTarget platform` is deprecated. Use `platform.rust.rustcTarget` instead.
evaluation warning: `rust.toRustTarget platform` is deprecated. Use `platform.rust.rustcTarget` instead.
evaluation warning: `rust.toRustTarget platform` is deprecated. Use `platform.rust.rustcTarget` instead.
evaluation warning: `rust.toRustTarget platform` is deprecated. Use `platform.rust.rustcTarget` instead.
evaluation warning: `rust.toRustTarget platform` is deprecated. Use `platform.rust.rustcTarget` instead.
evaluation warning: `rust.toRustTarget platform` is deprecated. Use `platform.rust.rustcTarget` instead.
```
Note that in my …
> Fix compatibility warning with nixpkgs >= NixOS 24.11

- README.rst
This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org/
ref: https://github.com/NixOS/foundation/issues/113
> README: point to new NixOS wiki

- firefox-overlay.nix
error: function 'wrapper' called with unexpected argument 'desktopName'
at …/nixpkgs/pkgs/applications/networking/browsers/firefox/wrapper.nix:27:5:
26|   wrapper =
27|     { applicationName ? browser.binaryName or (lib.getName browser) # Note: this is actually *binary* name and is different from browser.passthru.applicationName, which is *app* name!
|     ^
28|     , pname ? applicationName
See https://github.com/NixOS/nixpkgs/commit/b856437376fd346ed9054a671ec602eff16f496f.
> Fix evaluation error as of NixOS/nixpkgs#377863
