default.nix, pkgs/firefox-dev-bin/default.nix, pkgs/firefox-dev-bin/dev_sources.nix, pkgs/firefox-dev-bin/generate_sources_dev.rb
Might this repo be a better host for firefox developer edition?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/garbas/nixpkgs-mozilla/9)
=> Firefox dev bin

README.rst, rust-overlay-install.sh
=> Document how to use the Rust overlay

rust-overlay.nix
Currently, if you install the "rust" package, you only install rustc,
cargo and rust-std. With this patch, the rust package automatically
installs all packages that are listed as extension. So, you can use
"rustc --print sysroot" to build a path to the rust-src.
Solves: #16
=> Adds support to install all extensions of rust as one package

rust-overlay.nix
Be more explicit with where bindings are coming from.
=> Remove with statements.

README.rst
That release is now the current one :)
=> Remove obsolete warning

pkgs/firefox-nightly-bin/sources.nix
Also took the opportunity to change download link to HTTPS.
=> firefox-nightly-bin: 56.0a1-20170622100312 -> 56.0a1-20170703100343

rust-overlay.nix
Tested with `rustc 1.19.0-nightly (d47cf08d5 2017-05-28)`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/nixpkgs-mozilla/38)
=> rust-overlay: install bash_completions to share/

rust-overlay.nix
@garbas please review
Close #48
=> Handle the missing bash_completion situation

rust-overlay.nix
Okay, now I need cross compilation support :D
I began to add support for installing cross compilation targets, but at the moment it is dirty. 
The problem is, that some targets like "mips-unknown-linux-musl" just exist for the "rust-std" extension. Next problem is, that if I install the rust package I have to add "rust-std" as extra extension although it already will be installed by the rust package.
Here is my current default.nix:
```nix
with import <nixpkgs> {}; 
let 
myrust = (rustChannels.stable.rust.override { extensions = [ "rust-src" "rust-std" ]; extCrossTargets = [ "mips-unknown-linux-musl" ]; });
in
stdenv.mkDerivation {
name = "rust-dev";
buildInputs = [ myrust ];
}
```
I'm open for all kind of improvements^^
---
This change is [<img …
=> First attempt to support installing cross compilation targets

rust-overlay.nix
=> Checks that no extensions are missing

lib/parseTOML.nix
This pull request makes use of the yet to be introduce `builtins.split` function in Nix 1.12 (https://github.com/NixOS/nix/pull/1516).
Note that with Nix 1.12, we cannot just rely on the same algorithm as used previously as it leads to an infinite recursion or a fake memory limit of `builtins.match`.
This patch changes the back-end implementation of the tokenizer in order to switch between `builtins.split` implementation or `builtins.match` implementation, if not available.
This patch is tested with both Nix 1.11.13 and Nix 1.12.
With this patch Nix 1.12 is ~10% faster.
(fix #33, fix #40)
=> TOML parser: Use builtins.split instead of match.

README.rst, firefox-overlay.nix, release.nix, rust-overlay.nix
cc @garbas 
And after that, let spread the words.
=> Wrap Auto-updating expression under the 'latest' attribute.

README.rst
=> README: usage example

firefox-overlay.nix
Nix 2.0 introduced an regression that causes stack overflow on NixOS 18.03 in firefox-overlay (https://github.com/NixOS/nix/issues/2147).
I've replaced usage of `match` builtin with my own function that uses `split` and fallbacks to `match` if `split` is not available (since Nix 1.x do not have it).
So this should work both on Nix 2.0 and Nix 1.x.
Fixes #90.
=> firefox-overlay: workaround buggy builtins.match

README.rst, firefox-overlay.nix
=> Flesh out documentation about Firefox use and development

firefox-overlay.nix
=> Use buildhub.json's unique URLs for nightly builds

rust-overlay.nix
Using builtins.fetchurl breaks the assumption in nixpkgs that all outputs of derivations that
can access the network are fixed-output. This is the behaviour that we want when following the `latest`
rust channels, but in some cases we want full reproducability. One example is in building rust projects with hydra, hydra
by default does not accept derivations containing builtins.fetchurl.
This commit adds support for an optional attribute to the `rustChannelOf` function, the attribute
is the `sha256` of the manifest file that we wan't to use.
By calling
```nix
rustChannelOf {
channel = "nightly";
date = "2019-07-09";
sha256 = "1k20hnz20var23zjhm055ymhfjpymnijfp98c387855lbsaqwhk8";
};
```
We get a fixed output derivation for the rust toolchain.
The old behaviour is kept as well, so by calling …
=> Add support for fixed output rust channels

firefox-overlay.nix
After verification, any failure which happens during the postFecth command will
cause the failure of the derivation, and cause the output to not be reused.
This is a little painful to have these 2 different strategies for downloading
nightly and beta/releases versions, but there is no common ground to use for
both.
(Fix #199 )
=> Check Firefox Nightly signature after fetching the tarball.

pkgs/phlay/default.nix
Without this update, I got error messages as follow:
```
error conduit[ERR-CONDUIT-CORE]: Undefined index: rev
```
=> Update phlay: 0.2.0 -> 0.2.3

rust-overlay.nix
This PR adds basic support for Rust toolchain files which are formatted as TOML. The only requirement is that they have the extension `.toml`, but that could be lifted if you know how to catch errors in Nix (I don't).
As it is you can provide `{ rustToolchain = ./path/to/your-rust-toolchain.toml }` and things should just work.
=> Support TOML-formatted rust-toolchain files

firefox-overlay.nix
`verifyFileAuthenticity` now asserts that the checksums it’s verifying really contain the file to be verified. Also, it now accepts SHA-256 hashes of the checksum files themselves, so that after storing the result of an impurely evaluated `versionInfo` call, one can build `firefoxVersion` in pure evaluation mode. This is necessary for flake-firefox-nightly:
- colemickens/flake-firefox-nightly#3
=> Improve file authenticity check; fix to work in pure evaluation mode

firefox-overlay.nix
=> firefox-nightly-bin: preserve old nativeBuildInputs

firefox-overlay.nix
=> chore: update repository url

firefox-overlay.nix
working version of @hneiva's PR (unless I'm missing something :thinking: )
=> fix: Switch firefox file extension depending on version
